name: CI and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build project
        run: ./mvnw clean verify

      - name: Trigger Jenkins job
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TRIGGER_TOKEN }}
        run: |
          curl -X POST "$JENKINS_URL/generic-webhook-trigger/invoke?token=$JENKINS_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"from":"github-actions","branch":"${{ github.ref_name }}"}'

